## Get Started With Numpy

#### Installing numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


#### Importing Numpy

In [2]:
import numpy as np

#### Checking the version

In [3]:
print(np.__version__)

1.21.5


## Creating Numpy array

In [4]:
list = [1, 2, 3,  4, 5, 6, 7] # created list.
print(list)
array = np.array(list) #converting list to array.
print(array)

[1, 2, 3, 4, 5, 6, 7]
[1 2 3 4 5 6 7]


-> Numpy is said to be faster than list because:

-> Numpy array are stored in one continuous place in memory unlike list so processes can access and manipulate them very efficiently 

#### Checking the type 

In [5]:
print(type(list))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


## Dimensions in Array

In [6]:
dim0 = np.array(1)# 0-dimensional array
print(dim0)

print()

dim1 = np.array([1, 2, 3, 4])# 1-dimensional array
print(dim1)
print()


dim2 = np.array([[1, 2, 3], [4, 5, 6]]) # 2-dimension array.
print(dim2)

print()

dim3 = np.array([[[1, 2, 3,], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(dim3)



1

[1 2 3 4]

[[1 2 3]
 [4 5 6]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### Checking the dimension

In [7]:
print(dim0.ndim) # 0-dimension array
print(dim1.ndim) # 1-dimensional array
print(dim2.ndim) # 2-dimensional array
print(dim3.ndim) # 3-dimensional array

0
1
2
3


### Higher Dimensiol Arrays

An array can have any number of dimensional 

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], ndmin = 7)
print(arr) # prints 7-dimensional array.

[[[[[[[1 2 3 4 5 6 7 8 9 0]]]]]]]


## Accessing Array

#### Indexing in 1-dimensional array

In [9]:
print(dim1[1]) # prints the second element in 1-dim array.


2


#### Indexing in 2-dimensional array

In [10]:
print(dim2[0, 1])

2


#### Indexing in 3-dimensional array

In [11]:
print(dim3[0, 1, 0])

4


# Slicing Numpy Array

In [12]:
print([dim1[1:5]]) # slicing 1-dimensional array
print(dim2[1, 1:]) # slicing 2-dimensional array

[array([2, 3, 4])]
[5 6]


##  Numpy Data Types

###  Checking Data Type of an Array

In [13]:
print(dim1.dtype)

int32


In [14]:
fruits = np.array(['apple', 'banana', 'cherry'])
print(fruits.dtype)

<U6


In [15]:
arr1 = np.array([1, 2, 3, 4, 5], dtype ='S')
print(arr1)
print(arr1.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [16]:
arr2 = np.array([1, 2, 3, 4, 5], dtype = 'i4')
print(arr2)
print(arr2.dtype)

[1 2 3 4 5]
int32


In [17]:
arr3 = np.array([1.1, 2.1, 3.1])
newarr3 = arr3.astype('i') # converting float to intergeer.
print(newarr3)
print(newarr3.dtype)

[1 2 3]
int32


In [18]:
arr4 = newarr3.astype(bool) # converting interger to boolean
print(arr4)
print(arr4.dtype)

[ True  True  True]
bool


## Copy and View

The main difference between a copy and a view of an array is that the copy is a new array and the view is just an original array


->The copy the data and any changes made to the copy will not affect the original array and will not be affected by changes made to the original array.


->The view does not own the data and any changes made to it will affect the original array and the changes made to the original will affect the view


####  Copy

In [19]:
original = np.array([1, 2, 3, 4, 5])
copied_original = original.copy()

original[0] = 40 # change made to original does not affect the copy


print(original)
print(copied_original)

[40  2  3  4  5]
[1 2 3 4 5]


#### View

In [20]:
original1 = copied_original
original_view = original1.view()
original1[0] = 51 # change made to the original data affect the view

print(original1)
print(original_view)

original_view[1] = 52 # change made to the view affect the original.
print(original_view)

[51  2  3  4  5]
[51  2  3  4  5]
[51 52  3  4  5]


###  Checking if array own its data

'base' fuction is used to check if an array own its data and return 'None' if true.

In [21]:
print(original.base) # owns the data
print(original_view.base) # doesn't own the data

None
[51 52  3  4  5]


##  Numpy shape

Shape is the number of element is a given array dimesional

In [22]:
arr4 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]])
print(arr4.shape) # returns the tuple. 

# This means that the array has 2 dimensions, where each dimension has 5 elements.

(2, 5)


## Numpy reshape

reshape means changing the shape of and array i.e it's dimensions and elements in each dimension

In [23]:
arr5 = np.arange(14) # returns a range of numbers from 0 to 14 and does not include 14.

print(arr5) # a 1-dimensional array

print(arr5.ndim) # check the number of dimension. print 1 to indicate that the array is 1-dimensional

reshape_arr5 = arr5.reshape(2, 7) # reshape 1-dim  with 14 element to 2-dim with 7 elements each
print(reshape_arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
1
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]


In [24]:
arr6 = np.arange(1, 13)

print(arr6)
new_arr6 = arr6.reshape(2, 3, 2) #1-dim to 3-dim
print(new_arr6)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


####  Flattening The Array

Flattening means converting a multidimensional array into a 1D array.


In [25]:
flatten_new_arr6 = new_arr6.reshape(-1)
print(flatten_new_arr6)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Numpy Array Iterating


Iterating means going through the array elements one by one

####  iterating 1-D

In [26]:
one_dim = np.array([1, 2, 3])
for one in one_dim:
    print(one) 

1
2
3


#### Iterating 2-D

In [53]:
two_dim = np.array([[1, 2, 3], [4, 5, 6]])
for tw in two_dim:
    for two in tw:
        print(two)

1
2
3
4
5
6


####  3-D iteration

In [54]:
arr7 = np.arange(1, 13).reshape(2, 3 , 2)


for x in arr7:
    for y in x:
        for z in y:
            print(z) # iterating 3-D elements
    

1
2
3
4
5
6
7
8
9
10
11
12


#### Iterating using nditer

In [55]:
x_array = arr7
for arr in np.nditer(x_array):
    print(arr)

1
2
3
4
5
6
7
8
9
10
11
12


##  Array concatenation

-> Means joining two or more array in a single array.

In [56]:
old_array = np.array([56, 73, 56])
old_array1 = np.array([34, 33, 70])
concate = np.concatenate((old_array,  old_array1))
print(concate)


[56 73 56 34 33 70]


#### Join two 2-D arrays along rows (axis=1):

In [57]:

arrx = np.array([[14, 2], [13, 42]])

arry = np.array([[5, 60], [71, 8]])

arrz = np.concatenate((arrx, arry), axis=1)

print(arrz)

[[14  2  5 60]
 [13 42 71  8]]


###  Joining Arrays Using Stack Functions

 ->Stacking is same as concatenation, the only difference is that stacking is done along a new axis.


->We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.


->We pass a sequence of arrays that we want to join to the stack() method along with the axis.

In [58]:
arrx1 = np.array([14, 21, 39])

arry1 = np.array([7, 25, 4])

arrz1 = np.stack((arrx1, arry1), axis=1)

print(arrz1)

[[14  7]
 [21 25]
 [39  4]]


### Stacking Along Rows

-> hstack() to stack along rows.

In [59]:
arrz2 = np.hstack((arrx1, arry1))
print(arrz2)

[14 21 39  7 25  4]


### Stacking Along Columns

-> vstack()  to stack along columns.

In [62]:
arrz3 = np.vstack((arrx1, arry1))
print(arrz3)

[[14 21 39]
 [ 7 25  4]]


### Stacking Along Height (depth)

-> dstack() to stack along height, which is the same as depth.

In [63]:
arrz4 = np.dstack((arrx1, arry1))
print(arrz4)

[[[14  7]
  [21 25]
  [39  4]]]


### Splitting NumPy Arrays

->Splitting is reverse operation of Joining.


->Joining merges multiple arrays into one and Splitting breaks one array into multiple.


->We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [65]:
arrx2 = np.array([23, 12, 55, 9, 51, 30])

arry2 = np.array_split(arrx2, 3)

print(arry2)

[array([23, 12]), array([55,  9]), array([51, 30])]
